In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [3]:
np.random.randint(50,size=100,high=101)

array([ 68,  53,  54,  64,  80,  94,  74,  74, 100,  93,  90,  64,  76,
        52,  60,  54,  54,  89,  69,  68, 100,  58,  58,  69,  59,  73,
        67,  58,  62,  80,  85,  63,  79,  59,  86,  93,  55,  73,  70,
       100,  99,  67,  86,  61,  59,  59,  78,  69,  75,  88,  77,  50,
        96,  70,  67,  62,  80,  52,  90,  75,  76,  89,  85,  92,  91,
        70,  77,  96,  75,  61,  97,  92,  60,  98,  97,  86,  75,  64,
        72,  59,  91,  73,  51,  85,  72,  59,  68,  65,  77,  86,  69,
        93,  70,  50,  94,  67,  99,  51,  64,  83])

In [5]:
content = np.random.randint(50,size=(50,5),high=101)

In [6]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=range(1,51),
             columns=['國文','英文','數學','地理','歷史'])
df1

國文   英文   數學   地理   歷史
1    76   80   91   77   59
2    57   66   99   84   63
3    90   75   81   66   64
4    73   72   51   50   87
5    65   78   88   55   70
6    63   82   61   90   58
7    78   62   53   58   97
8    68   91   83   84   96
9    97   99   52   83   99
10   51   96   97   80   79
11   76   69   74   55   69
12   79   78   79   93   52
13  100   55   80   52   76
14   58   70   88   78   61
15   57   74   88   64   61
16   77   50   74   51   75
17   88   65   84   60   97
18   56   81   87   80   75
19   80   76   70   91  100
20   60   63   93   80   93
21   71  100   77   93   90
22   76   84   93   80   61
23   88   89   79   74  100
24   73   52  100   53   65
25   86   99   96   97   83
26   50   92   84   74   62
27   55   97   89   61   60
28   88   86   66   69   81
29   78   72   52   51   88
30   71   91   52   57   51
31   55   50   93   56   70
32   63   70   73   87   87
33   79   57   84   67   72
34   71   60   55   74   77
35   58   78   67   50   80
36   90   58   81   50   99
37   77   51   51   95   72
38   83   84   91   79   92
39   89   57   64   50   71
40   54   95   51   99   69
41   55   50   95   98   69
42   57   88   71   92   70
43   63   73   59   93   95
44   58   50   69   85   72
45   99   64   98   63   74
46   88   64   87   64   99
47   79   54   84   63   74
48   85   88   96   94   82
49   53   62   70   93   93
50   85   66   90  100   79

In [7]:
df1['國文'] + df1['英文'] + df1['數學'] + df1['地理'] + df1['歷史']

1     383
2     369
3     376
4     333
5     356
6     354
7     348
8     422
9     430
10    403
11    343
12    381
13    363
14    355
15    344
16    327
17    394
18    379
19    417
20    389
21    431
22    394
23    430
24    343
25    461
26    362
27    362
28    390
29    341
30    322
31    324
32    380
33    359
34    337
35    333
36    378
37    346
38    429
39    331
40    368
41    367
42    378
43    383
44    334
45    398
46    402
47    354
48    445
49    371
50    420
dtype: int64