In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [3]:
np.random.randint(50,size=100,high=101)

array([ 68,  53,  54,  64,  80,  94,  74,  74, 100,  93,  90,  64,  76,
        52,  60,  54,  54,  89,  69,  68, 100,  58,  58,  69,  59,  73,
        67,  58,  62,  80,  85,  63,  79,  59,  86,  93,  55,  73,  70,
       100,  99,  67,  86,  61,  59,  59,  78,  69,  75,  88,  77,  50,
        96,  70,  67,  62,  80,  52,  90,  75,  76,  89,  85,  92,  91,
        70,  77,  96,  75,  61,  97,  92,  60,  98,  97,  86,  75,  64,
        72,  59,  91,  73,  51,  85,  72,  59,  68,  65,  77,  86,  69,
        93,  70,  50,  94,  67,  99,  51,  64,  83])

In [4]:
np.random.randint(50,size=(50,5),high=101)

array([[ 72,  88,  97,  55,  54],
       [ 74,  77,  76,  93,  51],
       [ 67,  55,  51, 100,  78],
       [ 92,  86,  54,  75, 100],
       [ 62,  82,  75,  89,  86],
       [ 99,  56,  90, 100,  66],
       [ 90,  63,  52,  57,  64],
       [ 52,  99,  74, 100,  68],
       [ 58,  73,  85,  68,  98],
       [ 98,  72,  71,  90,  95],
       [ 80,  90,  77,  74,  67],
       [ 94,  87,  55,  97,  72],
       [ 71,  91,  58, 100,  69],
       [ 62,  67,  53,  77,  79],
       [ 65,  93,  59,  90,  76],
       [ 95,  87,  54,  85,  57],
       [ 77,  54,  65,  84,  67],
       [ 92,  81,  60,  69,  55],
       [ 64,  91,  66,  95,  60],
       [ 50,  79,  61,  60,  93],
       [ 79,  85,  77,  86,  93],
       [ 70,  98,  50, 100,  81],
       [ 59,  60,  88,  61,  74],
       [ 76,  64,  95,  65,  53],
       [ 62,  59,  66,  61,  95],
       [ 69,  81,  81,  88,  86],
       [ 78,  57,  85,  92,  70],
       [ 87,  51,  52,  85,  67],
       [ 51,  92,  66,  52,  84],
       [ 86,  